include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-rtp2httpd
PKG_VERSION:=1.0.0
PKG_PO_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI Support for rtp2httpd
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+rtp2httpd

PKG_MAINTAINER:=Stackie Jia <jsq2627@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
