name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    name: Run (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6

      - name: Build rtp2httpd
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_AGGRESSIVE_OPT=ON
          cmake --build build -j$(getconf _NPROCESSORS_ONLN)

      - uses: astral-sh/setup-uv@v7

      - name: Run E2E tests
        run: ./scripts/run-e2e.sh

  e2e-freebsd:
    runs-on: ubuntu-latest
    name: Run (freebsd)
    steps:
      - uses: actions/checkout@v6

      - name: Run E2E tests in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg install -y bash cmake python314 uv
          run: |
            export UV_PYTHON=/usr/local/bin/python3.14
            export UV_PYTHON_DOWNLOADS=never
            cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_AGGRESSIVE_OPT=ON
            cmake --build build -j$(sysctl -n hw.ncpu)
            ./scripts/run-e2e.sh
